// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzTktXgjlgEqd8E6t0k6HzWv03xyBErFY',
    appId: '1:109927117800:web:86c4c70da6b56b87e0aa5d',
    messagingSenderId: '109927117800',
    projectId: 'mr-lowat-bakery',
    authDomain: 'mr-lowat-bakery.firebaseapp.com',
    storageBucket: 'mr-lowat-bakery.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6zFOUxAqr755n0bN_LTlTrDqxN2bAT5g',
    appId: '1:109927117800:android:8175b5870635aa3ce0aa5d',
    messagingSenderId: '109927117800',
    projectId: 'mr-lowat-bakery',
    storageBucket: 'mr-lowat-bakery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKvb6CD41hQvKjBeUWOA6PxLb3_VtK26g',
    appId: '1:109927117800:ios:1a80b68035400295e0aa5d',
    messagingSenderId: '109927117800',
    projectId: 'mr-lowat-bakery',
    storageBucket: 'mr-lowat-bakery.firebasestorage.app',
    iosClientId: '109927117800-4u6s3m2n96caj4esise7pr2rvmbmaj1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrLowatBakery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKvb6CD41hQvKjBeUWOA6PxLb3_VtK26g',
    appId: '1:109927117800:ios:1a80b68035400295e0aa5d',
    messagingSenderId: '109927117800',
    projectId: 'mr-lowat-bakery',
    storageBucket: 'mr-lowat-bakery.firebasestorage.app',
    iosClientId: '109927117800-4u6s3m2n96caj4esise7pr2rvmbmaj1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrLowatBakery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzTktXgjlgEqd8E6t0k6HzWv03xyBErFY',
    appId: '1:109927117800:web:4a7f617b93367919e0aa5d',
    messagingSenderId: '109927117800',
    projectId: 'mr-lowat-bakery',
    authDomain: 'mr-lowat-bakery.firebaseapp.com',
    storageBucket: 'mr-lowat-bakery.firebasestorage.app',
  );
}
